### ISSUE TITLE
 Tokenizer Parallelism Warning and Slow Image Selection Process

### ISSUE THREAD

**Issue by x2x5** [aim-uofa/OIR#4]
Hi, congratulations on your ICLR accepted work! It’s really an interesting project. I tried running the code and encountered some warnings that I don’t fully understand. The warnings are as follows:

```
Inversion ...
Candidate images generation ...
Optimal candidate selection ...
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
```

Does this warning indicate that I might have done something wrong when running the code?

Another question is about the image selection process. On an A100 40GB GPU, I noticed that the generation of images isn’t very slow (it takes only a few minutes). However, I was surprised by how time-consuming the process of finding the best image is. While monitoring GPU usage, I observed that it doesn't seem to be using the GPU during the selection phase. Is this behavior normal?

Thank you for your help!

**Comment by ZhenYangCS** [comment]
**First question**: I would like to know what version of your diffusers is. This slow speed usually related to the diffusers version?

**Second question**: In this method, in order to find the best image in parallel, we need to repeat the diffusers t (https://github.com/aim-uofa/OIR/blob/main/utils/candidate_images_generation.py#L47), which may cause unknown errors on different diffusers versions. So it may also be a diffusers version problem.

The version I was using was diffusers==0.16.1


This version issue is indeed distressing. In fact, I am also planning to rewrite a better github repository recently, which will allow OIR to run on different models. However, I have been busy recently and cannot guarantee how long it will take to complete. The new version that will be completed will have a more standardized format.

**Comment by x2x5** [comment]
> **First question**: I would like to know what version of your diffusers is. This slow speed usually related to the diffusers version?
> 
> **Second question**: In this method, in order to find the best image in parallel, we need to repeat the diffusers t (https://github.com/aim-uofa/OIR/blob/main/utils/candidate_images_generation.py#L47), which may cause unknown errors on different diffusers versions. So it may also be a diffusers version problem.
> 
> The version I was using was diffusers==0.16.1
> 
> This version issue is indeed distressing. In fact, I am also planning to rewrite a better github repository recently, which will allow OIR to run on different models. However, I have been busy recently and cannot guarantee how long it will take to complete. The new version that will be completed will have a more standardized format.

Thanks for your quick feedback~

To be clear, I only tired single object python file, because I think it's easier to start.

I'm using `diffusers==0.31.0`, which is a very recent version. I found that adding the following code might resolve the warning about parallel:

```python
import os
os.environ["TOKENIZERS_PARALLELISM"] = "false"
```

I reran the code using the example (with 3 word changes to generate 3 images) and recorded the execution times:

```
Inversion time: 11 seconds
Candidate images generation time: 317 seconds
Optimal candidate selection time: 86 seconds
per image: (11+317+86)/3 == 414/3 == 138 seconds
```

I find these times (138 seconds for one image generation) to be acceptable.
